from tempfile import NamedTemporaryFile
import pandas as pd
import streamlit as st
import pysrt
import re
import pickle
import nltk

nltk.download('stopwords')
nltk.download('punkt')
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from pymystem3 import Mystem

st.title('Определение уровня английского языка в фильмах')
st.header('Загрузите файл с субтитрами фильма и алгоритм определит уровень:')


def load(file):
    with open(file, 'rb') as fid:
        return pickle.load(fid)


logreg = load('model.pcl')

vectorizer = load('vectorizer.pcl')

uploaded_file = st.file_uploader("Choose a .srt file", type="srt")

if uploaded_file is not None:
    with NamedTemporaryFile(suffix='.srt', delete=False) as tempfile:
        tempfile.write(uploaded_file.getbuffer())
        sub = pysrt.open(tempfile.name, encoding='utf-8')
    texts = sub.text


    def prepare_text(text):
        del_n = re.compile('\n')
        del_tags = re.compile('<[^>]*>')
        del_brackets = re.compile('\([^)]*\)')
        clean_text = re.compile('[^а-яa-z\s]')
        del_spaces = re.compile('\s{2,}')
        text = del_n.sub(' ', str(text).lower())
        text = del_tags.sub('', text)
        text = del_brackets.sub('', text)
        res_text = clean_text.sub('', text)
        return del_spaces.sub(' ', res_text)


    stop_words = stopwords.words('english')


    def del_stopwords(text):
        clean_tokens = tuple(
            map(lambda x: x if x not in stop_words else '', word_tokenize(text))
        )
        res_text = ' '.join(clean_tokens)
        return res_text


    m = Mystem()


    def lemmatize(text):
        lemmatized_text = ''.join(m.lemmatize(text))
        return lemmatized_text.split('|')


    def transformation(subs):
        clean_sub_string = prepare_text(subs)
        clean_sub_string = del_stopwords(clean_sub_string)
        clean_sub_string = lemmatize(clean_sub_string)

        return clean_sub_string[0]


    words_a1 = ['through', 'than', 'nine', 'bar', 'internet', 'chicken', 'kilometre', 'door', 'interest', 'quarter',
                'like', 'email', 'high', 'guess', 'nose', 'upstairs', 'best', 'capital', 'cut', 'east', 'half', 'below',
                'eighteen', 'onion', 'park', 'favorite', 'people', 'positive', 'sit', 'smart', 'project', 'December',
                'never', 'science', 'usually', 'could', 'supermarket', 'piano', 'please', 'his', 'own', 'programme',
                'player', 'office', 'hotel', 'pig', 'work', 'change', 'see', 'culture', 'find', 'Friday', 'live',
                'bike', 'quickly', 'sea', 'tourist', 'son', 'bedroom', 'aunt', 'job', 'umbrella', 'bored', 'hand',
                'send', 'as', 'miss', 'write', 'bag', 'open', 'egg', 'club', 'common', 'thank', 'cup', 'evening',
                'fifth', 'banana', 'week', 'before', 'believe', 'market', 'Tuesday', 'room', 'yellow', 'without',
                'thanks', 'all', 'list', 'explain', 'front', 'dog', 'April', 'nothing', 'check', 'useful', 'meaning',
                'still', 'easy', 'bird', 'plan', 'hard', 'hungry', 'any', 'build', 'far', 'pay', 'relax', 'August',
                'bus', 'complete', 'sure', 'expensive', 'us', 'pants', 'much', 'quick', 'nurse', 'every', 'terrible',
                'farmer', 'study', 'teenager', 'come', 'milk', 'coat', 'nobody', 'take', 'nice', 'weather', 'ago',
                'love', 'afternoon', 'great', 'eat', 'partner', 'sweater', 'sick', 'black', 'goodbye', 'theatre',
                'Thursday', 'me', 'rain', 'bath', 'together', 'million', 'dad', 'away', 'sister', 'near', 'OK', 'shirt',
                'two', 'basketball', 'jacket', 'painting', 'ready', 'dress', 'Sunday', 'month', 'to', 'else', 'body',
                'dirty', 'description', 'false', 'choose', 'possible', 'reading', 'building', 'poor', 'beer', 'head',
                'course', 'grandfather', 'wrong', 'girl', 'kind', 'friendly', 'wake', 'tonight', 'understand',
                'delicious', 'future', 'use', 'title', 'forget', 'baby', 'minute', 'hospital', 'food', 'excited',
                'opinion', 'color', 'perfect', 'sing', 'student', 'worker', 'shoe', 'teacher', 'fill', 'trousers',
                'grow', 'married', 'dark', 'above', 'Monday', 'return', 'phrase', 'fruit', 'waiter', 'play', 'strong',
                'vegetable', 'rice', 'bank', 'career', 'we', 'eleven', 'meal', 'period', 'metre', 'it', 'anyone',
                'history', 'again', 'taxi', 'warm', 'pretty', 'early', 'feel', 'doctor', 'snake', 'favourite', 'free',
                'everybody', 'October', 'would', 'house', 'water', 'well', 'angry', 'space', 'time', 'when', 'do',
                'man', 'music', 'TV', 'flat', 'walk', 'face', 'or', 'difficult', 'always', 'online', 'reader', 'who',
                'paint', 'sugar', 'buy', 'driver', 'want', 'morning', 'life', 'slow', 'prepare', 'euro', 'bread',
                'back', 'pepper', 'juice', 'brother', 'autumn', 'stand', 'dear', 'June', 'I', 'journey', 'begin',
                'tree', 'art', 'healthy', 'key', 'across', 'turn', 'blog', 'oh', 'long', 'big', 'ocean', 'not', 'film',
                'passport', 'festival', 'program', 'say', 'bring', 'actor', 'blond', 'compare', 'car', 'mom', 'famous',
                'cheese', 'end', 'soon', 'my', 'day', 'no one', 'radio', 'large', 'south', 'few', 'city', 'airport',
                'cream', 'topic', 'leave', 'lesson', 'natural', 'red', 'salad', 'midnight', 'them', 'writing', 'listen',
                'way', 'modern', 'vacation', 'blonde', 'cousin', 'trip', 'their', 'put', 'grey', 'tomorrow', 'street',
                'amazing', 'practise', 'chair', 'gym', 'paragraph', 'idea', 'spend', 'can', 'enough', 'land', 'her',
                'lion', 'tell', 'language', 'baseball', 'swimming', 'foot', 'sound', 'fast', 'she', 'video', 'left',
                'bad', 'boyfriend', 'will', 'funny', 'the', 'no', 'object', 'four', 'meeting', 'make', 'popular',
                'learn', 'holiday', 'glass', 'place', 'diet', 'twice', 'drink', 'three', 'beginning', 'everyone',
                'some', 'product', 'shower', 'dictionary', 'husband', 'movie', 'statement', 'maybe', 'picture',
                'design', 'think', 'policeman', 'visit', 'college', 'so', 'remember', 'road', 'table', 'improve', 'ice',
                'wear', 'break', 'menu', 'actress', 'interview', 'scientist', 'fact', 'light', 'moment', 'cafe', 'here',
                'artist', 'quiet', 'adult', 'country', 'have', 'lunch', 'awesome', 'carry', 'imagine', 'traffic', 'off',
                'line', 'September', 'feeling', 'quite', 'sport', 'family', 'February', 'probably', 'restaurant',
                'chart', 'action', 'between', 'hot', 'for', 'join', 'green', 'fish', 'bye', 'kitchen', 'soup', 'they',
                'ask', 'pink', 'each', 'once', 'T-shirt', 'test', 'mouse', 'river', 'travel', 'note', 'ball', 'create',
                'answer', 'thousand', 'another', 'plane', 'price', 'keep', 'magazine', 'match', 'its', 'spelling',
                'theater', 'sun', 'into', 'area', 'shop', 'island', 'call', 'coffee', 'telephone', 'spring', 'farm',
                'text', 'tooth', 'decide', 'fire', 'shopping', 'by', 'at', 'business', 'dish', 'name', 'phone', 'even',
                'your', 'garden', 'report', 'sixty', 'ever', 'fly', 'rule', 'show', 'skill', 'wonderful', 'important',
                'newspaper', 'brown', 'short', 'arrive', 'date', 'hair', 'pair', 'just', 'interested', 'mother',
                'negative', 'second', 'style', 'article', 'cook', 'father', 'if', 'seven', 'type', 'mountain', 'enjoy',
                'up', 'boot', 'very', 'bottle', 'cost', 'help', 'tea', 'forty', 'dinner', 'song', 'winter', 'down',
                'fantastic', 'follow', 'move', 'nineteen', 'sorry', 'person', 'something', 'prefer', 'hat', 'behind',
                'cold', 'draw', 'dollar', 'lot', 'sell', 'more', 'party', 'after', 'interesting', 'ten', 'gray',
                'customer', 'wife', 'guitar', 'one', 'because', 'he', 'hundred', 'little', 'book', 'cannot', 'member',
                'mouth', 'university', 'someone', 'reason', 'CD', 'health', 'police', 'purple', 'must', 'truck',
                'chocolate', 'world', 'cent', 'real', 'concert', 'cow', 'also', 'this', 'become', 'grandparent',
                'photo', 'hi', 'personal', 'exciting', 'practice', 'young', 'where', 'but', 'yesterday', 'point',
                'drive', 'camera', 'yard', 'thing', 'eye', 'often', 'machine', 'age', 'card', 'success', 'thirty',
                'writer', 'computer', 'good', 'full', 'library', 'section', 'six', 'station', 'centre', 'museum',
                'thirsty', 'everything', 'happy', 'most', 'cat', 'really', 'somebody', 'outside', 'store', 'thirteen',
                'neighbor', 'west', 'hate', 'first', 'final', 'center', 'wall', 'describe', 'information', 'repeat',
                'eight', 'pen', 'there', 'introduce', 'seventy', 'same', 'clothes', 'game', 'late', 'mile', 'flight',
                'letter', 'mall', 'special', 'that', 'order', 'o’clock', 'football', 'then', 'colour', 'DVD', 'piece',
                'let', 'around', 'village', 'fifteen', 'woman', 'situation', 'team', 'cool', 'fourteen', 'fine',
                'butter', 'hello', 'add', 'beautiful', 'post', 'similar', 'map', 'year', 'discuss', 'seventeen',
                'exercise', 'eighty', 'sentence', 'summer', 'fourth', 'leg', 'opposite', 'should', 'sixteen', 'win',
                'air', 'our', 'pound', 'snow', 'stop', 'ticket', 'blue', 'what', 'home', 'problem', 'teach', 'both',
                'downstairs', 'animal', 'group', 'correct', 'right', 'tired', 'today', 'cinema', 'start', 'Wednesday',
                'on', 'example', 'elephant', 'grandmother', 'ear', 'him', 'new', 'small', 'visitor', 'sometimes',
                'with', 'however', 'horse', 'true', 'need', 'January', 'wait', 'singer', 'sleep', 'finish', 'message',
                'clock', 'how', 'band', 'try', 'word', 'century', 'hear', 'story', 'dangerous', 'jeans', 'go', 'cake',
                'hour', 'star', 'under', 'neighborhood', 'ride', 'meet', 'last', 'you', 'activity', 'laugh', 'stay',
                'news', 'old', 'part', 'boy', 'arm', 'homework', 'white', 'fifty', 'over', 'get', 'March', 'afraid',
                'present', 'only', 'tomato', 'form', 'difference', 'weekend', 'north', 'past', 'bicycle', 'salt',
                'yourself', 'from', 'watch', 'desk', 'plant', 'detail', 'school', 'different', 'dance', 'swim',
                'toilet', 'cooking', 'company', 'and', 'third', 'climb', 'include', 'die', 'exam', 'fall', 'lie',
                'routine', 'boring', 'during', 'pencil', 'skirt', 'orange', 'happen', 'hope', 'pool', 'anything', 'too',
                'sheep', 'train', 'know', 'extra', 'carrot', 'clean', 'fun', 'main', 'which', 'dancing', 'lose', 'yes',
                'give', 'mum', 'May', 'child', 'dancer', 'mean', 'model', 'spell', 'subject', 'look', 'television',
                'cheap', 'sad', 'be', 'read', 'page', 'photograph', 'advice', 'November', 'bed', 'tall', 'busy',
                'money', 'now', 'number', 'of', 'hobby', 'floor', 'flower', 'night', 'birthday', 'town', 'address',
                'ninety', 'uncle', 'local', 'other', 'window', 'agree', 'dialogue', 'speak', 'hey', 'beach', 'meat',
                'geography', 'share', 'mistake', 'until', 'close', 'parent', 'about', 'neighbour', 'paper', 'classroom',
                'fat', 'talk', 'box', 'later', 'Saturday', 'yeah', 'sandwich', 'conversation', 'run', 'twenty',
                'welcome', 'question', 'in', 'July', 'class', 'apartment', 'twelve', 'event', 'tennis', 'bathroom',
                'better', 'breakfast', 'website', 'wine', 'out', 'result', 'five', 'next', 'girlfriend', 'potato',
                'bill', 'many', 'born', 'friend', 'rich', 'wash', 'daughter', 'meter', 'apple', 'boat', 'why']

    words_a2 = ['hill', 'oil', 'petrol', 'refuse', 'bar', 'cause', 'luck', 'pattern', 'equipment', 'argue', 'lost',
                'neck', 'appearance', 'realize', 'vehicle', 'cookie', 'tower', 'badly', 'complain', 'biology', 'almost',
                'medical', 'ground', 'smoke', 'award', 'distance', 'already', 'discussion', 'high', 'lab', 'material',
                'movement', 'oven', 'best', 'gate', 'appear', 'survey', 'upstairs', 'bone', 'jewelry', 'produce',
                'half', 'recent', 'media', 'while', 'informal', 'sign', 'printer', 'offer', 'injury', 'nowhere',
                'unfortunately', 'track', 'suggest', 'cartoon', 'comedy', 'thief', 'straight', 'polite', 'bottom',
                'please', 'his', 'own', 'average', 'bit', 'except', 'missing', 'platform', 'penny', 'mathematics',
                'loud', 'lamp', 'hall', 'avoid', 'definitely', 'foreign', 'desert', 'frog', 'figure', 'successful',
                'sea', 'perhaps', 'series', 'billion', 'essay', 'predict', 'condition', 'perform', 'as', 'stair',
                'prison', 'round', 'leader', 'pain', 'less', 'brain', 'before', 'normally', 'fan', 'single', 'soap',
                'habit', 'danger', 'exactly', 'site', 'ski', 'soldier', 'grass', 'energy', 'heavy', 'all', 'typical',
                'shut', 'underground', 'compete', 'usual', 'check', 'professor', 'abroad', 'arrange', 'soft', 'illness',
                'reach', 'poster', 'any', 'pay', 'sadly', 'empty', 'wooden', 'yet', 'character', 'quality', 'sure',
                'pants', 'industry', 'heat', 'researcher', 'alone', 'manner', 'bin', 'greet', 'pass', 'succeed',
                'broken', 'available', 'along', 'driving', 'weak', 'degree', 'themselves', 'according', 'ancient',
                'used', 'president', 'understanding', 'cross', 'somewhere', 'simple', 'transport', 'ship', 'ability',
                'decision', 'furniture', 'jump', 'musician', 'crowd', 'itself', 'knowledge', 'basketball', 'clerk',
                'queen', 'react', 'van', 'touch', 'noisy', 'electric', 'sir', 'although', 'chance', 'error', 'guide',
                'male', 'stamp', 'lovely', 'replace', 'percent', 'blood', 'attend', 'professional', 'purpose', 'scary',
                'smartphone', 'step', 'speaker', 'ourselves', 'button', 'future', 'use', 'taste', 'downtown', 'receive',
                'passenger', 'suggestion', 'plate', 'refrigerator', 'region', 'tourism', 'since', 'finally', 'mobile',
                'intelligent', 'lifestyle', 'dark', 'bridge', 'fever', 'god', 'herself', 'pet', 'pick', 'spider',
                'promise', 'permission', 'national', 'variety', 'direct', 'teaching', 'strange', 'alive', 'garbage',
                'fail', 'daily', 'hers', 'sailing', 'goal', 'stone', 'criminal', 'target', 'connect', 'free',
                'individual', 'zero', 'railway', 'record', 'tablet', 'certain', 'involve', 'tradition', 'feature',
                'extremely', 'general', 'everyday', 'comment', 'race', 'cloud', 'safe', 'publish', 'flat', 'candy',
                'suddenly', 'allow', 'per', 'express', 'awful', 'back', 'birth', 'continue', 'mark', 'state', 'notice',
                'finger', 'dear', 'experiment', 'king', 'climate', 'athlete', 'respond', 'side', 'salary', 'dead',
                'assistant', 'case', 'count', 'search', 'ocean', 'toy', 'lemon', 'factor', 'power', 'film', 'chat',
                'seem', 'employer', 'thinking', 'program', 'ill', 'onto', 'crime', 'competition', 'brilliant', 'chef',
                'dessert', 'colleague', 'enter', 'sneaker', 'accept', 'cycle', 'fashion', 'huge', 'rock', 'term', 'top',
                'ideal', 'affect', 'repair', 'shall', 'behavior', 'cry', 'mirror', 'fridge', 'wave', 'engine', 'score',
                'instruction', 'solution', 'whole', 'brush', 'schedule', 'lady', 'clothing', 'moon', 'journalist',
                'singing', 'runner', 'can', 'identify', 'print', 'impossible', 'land', 'architecture', 'learning',
                'baseball', 'anyway', 'church', 'tour', 'review', 'digital', 'divorced', 'request', 'experience',
                'route', 'several', 'worst', 'personality', 'himself', 'continent', 'size', 'uniform', 'holiday',
                'quietly', 'secondly', 'height', 'suppose', 'toward', 'knife', 'carpet', 'method', 'training', 'unit',
                'borrow', 'closet', 'pronounce', 'shout', 'farming', 'light', 'narrow', 'response', 'traveler', 'metal',
                'disease', 'adult', 'have', 'drug', 'burn', 'clever', 'musical', 'deep', 'thought', 'stress', 'lend',
                'blow', 'sheet', 'instead', 'symbol', 'between', 'advantage', 'kill', 'fish', 'further', 'device',
                'medicine', 'audience', 'gap', 'normal', 'camping', 'chemistry', 'rise', 'cupboard', 'golf', 'shape',
                'disagree', 'weight', 'reduce', 'active', 'inside', 'deal', 'electricity', 'hurt', 'screen',
                'explanation', 'novel', 'closed', 'surprised', 'matter', 'maths', 'network', 'motorcycle', 'organize',
                'specific', 'text', 'farm', 'fire', 'pleased', 'context', 'image', 'quantity', 'businessman', 'social',
                'trouble', 'worried', 'belt', 'save', 'expect', 'gallery', 'report', 'reporter', 'prize', 'fit',
                'airline', 'fly', 'sense', 'support', 'wild', 'stomach', 'bright', 'cell', 'secretary',
                'transportation', 'ending', 'technology', 'board', 'none', 'particular', 'second', 'plastic', 'care',
                'cook', 'castle', 'rest', 'extreme', 'profile', 'engineer', 'detective', 'fork', 'arrangement',
                'reception', 'square', 'teenage', 'ankle', 'cash', 'copy', 'effect', 'joke', 'least', 'rubbish',
                'campus', 'user', 'expression', 'math', 'electronic', 'unhappy', 'biscuit', 'invite', 'towel', 'chip',
                'recipe', 'field', 'soccer', 'drop', 'asleep', 'bear', 'alternative', 'after', 'mostly', 'temperature',
                'war', 'tie', 'owner', 'coach', 'steal', 'level', 'nature', 'little', 'book', 'overseas', 'dry',
                'anymore', 'anywhere', 'original', 'push', 'advertise', 'twin', 'argument', 'neither', 'wedding',
                'wood', 'worse', 'view', 'tidy', 'background', 'seat', 'attack', 'direction', 'lazy', 'smoking',
                'population', 'recycle', 'truck', 'hole', 'secret', 'recognize', 'position', 'cooker', 'bean', 'corner',
                'washing', 'analyze', 'adventure', 'employee', 'clear', 'data', 'immediately', 'sweet', 'happily',
                'charity', 'develop', 'guy', 'drive', 'gift', 'contain', 'progress', 'rude', 'such', 'director',
                'couple', 'hide', 'advertising', 'boss', 'document', 'likely', 'lucky', 'accident', 'good', 'surprise',
                'download', 'act', 'camp', 'helpful', 'forest', 'physics', 'sort', 'fix', 'gas', 'thick', 'outside',
                'heart', 'mine', 'store', 'invitation', 'conference', 'web', 'invention', 'scene', 'role', 'beef',
                'guest', 'regular', 'laptop', 'wow', 'first', 'jazz', 'attention', 'fight', 'final', 'manager',
                'collect', 'column', 'knock', 'patient', 'wish', 'exact', 'protect', 'physical', 'kid', 'ordinary',
                'myself', 'gun', 'against', 'process', 'crazy', 'nervous', 'wide', 'village', 'service', 'nearly',
                'actually', 'smell', 'rate', 'ah', 'easily', 'independent', 'instructor', 'insect', 'worry', 'earn',
                'bowl', 'hero', 'option', 'headache', 'catch', 'exist', 'invent', 'skin', 'amount', 'correctly',
                'pollution', 'recommend', 'stove', 'listener', 'shoulder', 'may', 'anybody', 'expert', 'international',
                'fresh', 'depend', 'thin', 'fear', 'nut', 'society', 'whose', 'diary', 'subway', 'surprising', 'low',
                'home', 'grocery', 'death', 'running', 'earth', 'clearly', 'downstairs', 'major', 'tip', 'raise',
                'memory', 'following', 'refer', 'strategy', 'traditional', 'lorry', 'valley', 'railroad', 'either',
                'start', 'mind', 'female', 'pub', 'ring', 'especially', 'attractive', 'circle', 'discover', 'focus',
                'mail', 'classical', 'possibility', 'sky', 'fishing', 'drama', 'virus', 'need', 'speed', 'jam', 'pop',
                'sleep', 'completely', 'environment', 'finish', 'incredible', 'wait', 'consider', 'winner', 'double',
                'comfortable', 'century', 'achieve', 'smile', 'scared', 'apply', 'sock', 'pocket', 'fair', 'possession',
                'star', 'voice', 'introduction', 'provide', 'wet', 'ride', 'wheel', 'source', 'advertisement', 'stage',
                'factory', 'last', 'drawing', 'stay', 'destroy', 'beat', 'fortunately', 'united', 'necessary',
                'careful', 'choice', 'electrical', 'separate', 'behave', 'based', 'belong', 'present', 'serious',
                'past', 'skiing', 'stupid', 'plant', 'disaster', 'behaviour', 'parking', 'fiction', 'pilot', 'designer',
                'yours', 'working', 'increase', 'eader', 'slowly', 'gold', 'third', 'jewellery', 'fall', 'coast',
                'manage', 'mention', 'department', 'instrument', 'app', 'pack', 'recording', 'system', 'hope', 'trash',
                'education', 'knee', 'palace', 'benefit', 'blank', 'included', 'train', 'certainly', 'fun', 'sail',
                'lift', 'trainer', 'cover', 'human', 'noise', 'rather', 'pull', 'employ', 'connected', 'discovery',
                'shake', 'look', 'dream', 'hold', 'cigarette', 'firstly', 'feed', 'credit', 'hockey', 'photograph',
                'recently', 'army', 'evidence', 'number', 'suit', 'hit', 'planet', 'sale', 'crowded', 'unusual',
                'officer', 'lead', 'laughter', 'middle', 'mayor', 'roof', 'painter', 'serve', 'might', 'elevator',
                'author', 'including', 'celebrity', 'opportunity', 'carefully', 'prevent', 'throw', 'excellent',
                'disappear', 'marry', 'lawyer', 'celebrate', 'community', 'close', 'kilometer', 'communicate', 'reply',
                'sauce', 'lock', 'flu', 'storm', 'fat', 'remove', 'talk', 'lecture', 'later', 'architect', 'creative',
                'forward', 'towards', 'run', 'speech', 'spoon', 'link', 'government', 'dentist', 'welcome', 'enormous',
                'flying', 'monkey', 'question', 'loudly', 'structure', 'law', 'able', 'relationship', 'solve', 'task',
                'traveller', 'item', 'code', 'organization', 'research', 'better', 'differently', 'everywhere', 'wind',
                'curly', 'lake', 'public', 'peace', 'silver', 'boil', 'tool', 'wash', 'control', 'among', 'block',
                'formal', 'season']

    words_b1 = ['theory', 'campaign', 'impact', 'force', 'kiss', 'impressive', 'favour', 'familiar', 'weigh', 'fasten',
                'layer', 'hurry', 'specifically', 'coloured', 'educate', 'award', 'like', 'weapon', 'ingredient',
                'statue', 'photography', 'cut', 'determined', 'while', 'balance', 'grain', 'talent', 'mood', 'smart',
                'lip', 'academic', 'lay', 'poetry', 'donate', 'location', 'practical', 'automatically', 'bury',
                'marketing', 'private', 'gentleman', 'relate', 'press', 'average', 'profession', 'except', 'category',
                'upset', 'celebration', 'drum', 'lonely', 'immediate', 'regularly', 'generally', 'valuable', 'supply',
                'survive', 'brand', 'freeze', 'live', 'pressure', 'percentage', 'signal', 'embarrassed', 'portrait',
                'export', 'effective', 'hand', 'appointment', 'previous', 'trade', 'secondary', 'limit', 'earthquake',
                'confirm', 'sensible', 'frighten', 'poem', 'wool', 'injure', 'assignment', 'discount', 'remain',
                'safety', 'account', 'directly', 'spirit', 'frightening', 'market', 'scan', 'measure', 'horrible',
                'historic', 'consist', 'costume', 'living', 'curtain', 'coal', 'ad', 'bend', 'receipt', 'qualify',
                'episode', 'keyboard', 'occasion', 'aim', 'escape', 'servant', 'bell', 'guilty', 'competitor', 'bomb',
                'amazed', 'exit', 'happiness', 'necessarily', 'supporter', 'still', 'container', 'path', 'leaf',
                'issue', 'string', 'impression', 'far', 'automatic', 'empty', 'frame', 'volunteer', 'version', 'remind',
                'ought', 'laboratory', 'southern', 'surface', 'suffer', 'performance', 'custom', 'authority',
                'currency', 'pass', 'magic', 'dirt', 'historical', 'smooth', 'truth', 'confident', 'property', 'tongue',
                'used', 'folk', 'belief', 'content', 'sand', 'poisonous', 'transport', 'identity', 'dust', 'shell',
                'addition', 'embarrassing', 'fry', 'covered', 'prediction', 'represent', 'touch', 'wing', 'sex',
                'successfully', 'net', 'friendship', 'photographer', 'annoying', 'slightly', 'standard', 'contrast',
                'expand', 'organized', 'decade', 'announce', 'documentary', 'resource', 'robot', 'head', 'wrong',
                'kind', 'departure', 'bride', 'mixture', 'iron', 'upon', 'import', 'base', 'hunt', 'cottage', 'cotton',
                'breathe', 'meanwhile', 'destination', 'participate', 'since', 'apart', 'politician', 'flow', 'leather',
                'port', 'unable', 'written', 'expedition', 'production', 'script', 'fixed', 'mental', 'clue', 'highly',
                'similarity', 'define', 'ghost', 'annoyed', 'guard', 'incredibly', 'bank', 'direct', 'relaxing',
                'consequence', 'pin', 'shine', 'tyre', 'ugly', 'require', 'tight', 'confused', 'warm', 'daily',
                'criminal', 'growth', 'risk', 'row', 'corn', 'gentle', 'planning', 'water', 'feature', 'eventually',
                'edge', 'comment', 'invest', 'race', 'reaction', 'viewer', 'face', 'flour', 'employment', 'treat',
                'backward', 'reference', 'slow', 'intend', 'expected', 'punish', 'ton', 'tiny', 'typically', 'clause',
                'unlike', 'state', 'unless', 'repeated', 'entry', 'proud', 'statistic', 'experiment', 'software',
                'colored', 'journey', 'nail', 'hire', 'battery', 'key', 'reflect', 'unemployed', 'count', 'surely',
                'queue', 'disappointing', 'fur', 'originally', 'painful', 'grade', 'heavily', 'dressed', 'program',
                'management', 'responsible', 'stuff', 'fashionable', 'ambition', 'pale', 'economy', 'poverty',
                'technical', 'function', 'client', 'fitness', 'equally', 'improvement', 'breath', 'enemy', 'contact',
                'development', 'garage', 'rent', 'imaginary', 'printing', 'cream', 'central', 'district',
                'unemployment', 'throat', 'marriage', 'entrance', 'total', 'mix', 'repair', 'bite', 'complaint',
                'protest', 'cap', 'intelligence', 'commit', 'vote', 'wave', 'talented', 'sharp', 'equal', 'countryside',
                'whole', 'mild', 'particularly', 'confuse', 'calm', 'silent', 'exhibition', 'bee', 'peaceful',
                'backwards', 'principal', 'worldwide', 'responsibility', 'plus', 'studio', 'tour', 'editor', 'advise',
                'request', 'politics', 'innocent', 'experience', 'entertainment', 'will', 'tail', 'related', 'medium',
                'glad', 'rare', 'worst', 'substance', 'federal', 'favor', 'IT', 'border', 'attraction', 'therefore',
                'nuclear', 'toe', 'entertain', 'engaged', 'place', 'royal', 'continuous', 'trend', 'appreciate', 'warn',
                'alcohol', 'communication', 'annoy', 'shiny', 'pan', 'slave', 'unfair', 'pretend', 'pleasure', 'gather',
                'brave', 'achievement', 'basis', 'coin', 'leading', 'revise', 'political', 'clever', 'personally',
                'musical', 'deep', 'effectively', 'organizer', 'symptom', 'combine', 'obviously', 'ambitious',
                'various', 'rarely', 'spread', 'stranger', 'further', 'presentation', 'indeed', 'remote', 'grateful',
                'liquid', 'prepared', 'recommendation', 'muscle', 'normal', 'respect', 'operation', 'cupboard', 'rise',
                'heating', 'once', 'sink', 'deal', 'northern', 'theme', 'profit', 'note', 'application', 'disadvantage',
                'investigate', 'promote', 'sample', 'tend', 'breathing', 'goods', 'unnecessary', 'reject', 'spring',
                'western', 'decorate', 'fire', 'involved', 'by', 'experienced', 'perfectly', 'influence', 'encourage',
                'throughout', 'murder', 'pot', 'fairly', 'click', 'commercial', 'waste', 'election', 'suitable', 'rule',
                'hurricane', 'located', 'agreement', 'advanced', 'highlight', 'powerful', 'row1', 'diamond', 'rough',
                'board', 'old-fashioned', 'uncomfortable', 'host', 'element', 'type', 'exchange', 'locate',
                'concentrate', 'currently', 'consumer', 'campus', 'move', 'soil', 'set', 'emotion', 'flood', 'racing',
                'convince', 'unlikely', 'drop', 'alternative', 'definite', 'alarm', 'needle', 'prove', 'candidate',
                'mystery', 'coach', 'content1', 'level', 'indoors', 'agent', 'overseas', 'doubt', 'prisoner', 'illegal',
                'horror', 'switch', 'original', 'push', 'frightened', 'range', 'scientific', 'captain', 'beauty',
                'difficulty', 'neither', 'worse', 'graduate', 'quotation', 'view', 'rope', 'stadium', 'reality',
                'whether', 'neighbourhood', 'pour', 'indirect', 'this', 'attitude', 'underwear', 'clear', 'retire',
                'disappointed', 'religion', 'headline', 'young', 'journal', 'point', 'basic', 'religious', 'yard',
                'seriously', 'whenever', 'ceiling', 'tin', 'age', 'centre', 'act', 'union', 'sort', 'technique',
                'staff', 'obvious', 'essential', 'competitive', 'mainly', 'cheerful', 'store', 'mine', 'passion',
                'prince', 'qualification', 'mad', 'eastern', 'helicopter', 'childhood', 'assist', 'hate', 'mud',
                'center', 'shelf', 'cloth', 'update', 'complex', 'fold', 'repeat', 'knock', 'package', 'hang',
                'retired', 'worth', 'security', 'intention', 'mall', 'that', 'rugby', 'channel', 'explore', 'honest',
                'excitement', 'analyse', 'judge', 'release', 'emergency', 'immigrant', 'reliable', 'loss', 'injured',
                'spicy', 'cool', 'primary', 'tire', 'arrival', 'administration', 'cultural', 'worry', 'fascinating',
                'producer', 'possibly', 'convenient', 'conclude', 'bake', 'connection', 'comparison', 'explode',
                'ignore', 'keen', 'till', 'win', 'highway', 'label', 'nor', 'cruel', 'fear', 'plot', 'bubble',
                'forever', 'tape', 'priest', 'tube', 'diagram', 'examine', 'engineering', 'admire', 'frequently',
                'chain', 'persuade', 'previously', 'outdoors', 'careless', 'tip', 'admit', 'silly', 'raise',
                'following', 'payment', 'file', 'tax', 'value', 'atmosphere', 'ring', 'summarize', 'punishment',
                'indicate', 'relative', 'lack', 'champion', 'occur', 'hardly', 'leisure', 'neat', 'relaxed', 'spending',
                'chapter', 'policy', 'need', 'alcoholic', 'killing', 'global', 'analysis', 'shift', 'double',
                'pleasant', 'fence', 'educated', 'frozen', 'luxury', 'fancy', 'chest', 'consume', 'go', 'chemical',
                'financial', 'qualified', 'poison', 'relation', 'ceremony', 'battle', 'generous', 'unpleasant',
                'literature', 'naturally', 'definition', 'quit', 'spoken', 'determine', 'afford', 'separate',
                'strength', 'kick', 'nation', 'attract', 'despite', 'collection', 'swim', 'accommodation', 'official',
                'whatever', 'apologize', 'reservation', 'climb', 'though', 'damage', 'trick', 'lie', 'announcement',
                'violent', 'warning', 'shoot', 'absolutely', 'mention', 'sculpture', 'fuel', 'duty', 'pack',
                'challenge', 'dislike', 'tent', 'benefit', 'aged', 'branch', 'extra', 'theirs', 'summary', 'simply',
                'pipe', 'sail', 'trainer', 'cover', 'wonder', 'importance', 'approximately', 'pull', 'strongly',
                'charge', 'claim', 'conclusion', 'latest', 'shake', 'environmental', 'victim', 'cheat', 'cheap',
                'effort', 'flag', 'spot', 'similarly', 'shy', 'totally', 'sudden', 'solid', 'now', 'due', 'native',
                'poet', 'sexual', 'suit', 'translate', 'setting', 'treatment', 'sailor', 'court', 'cable', 'lead',
                'local', 'mess', 'aware', 'current', 'divide', 'generation', 'ours', 'properly', 'album', 'economic',
                'legal', 'arrest', 'romantic', 'share', 'ban', 'roll', 'stick', 'close', 'narrative', 'slice', 'bother',
                'giant', 'fighting', 'outdoor', 'pray', 'quote', 'translation', 'educational', 'indoor', 'powder',
                'prayer', 'explosion', 'glove', 'better', 'ahead', 'attach', 'deliver', 'length', 'sight', 'result',
                'next', 'drunk', 'seed', 'youth', 'plenty', 'access', 'proper', 'princess', 'within', 'block', 'odd']

    words_b2 = ['mechanical', 'bar', 'favour', 'interpretation', 'heaven', 'crack', 'numerous', 'relatively', 'survey',
                'proof', 'produce', 'genuinely', 'significantly', 'proposal', 'aggressive', 'democracy', 'interact',
                'timing', 'bunch', 'psychological', 'funding', 'manufacturing', 'romance', 'somehow', 'reward',
                'proceed', 'obtain', 'collector', 'acre', 'darkness', 'exhibit', 'justice', 'leadership', 'vision',
                'counter', 'furious', 'instance', 'alongside', 'construction', 'adjust', 'firefighter', 'exit', 'bond',
                'corporation', 'specialize', 'makeup', 'obstacle', 'automatic', 'curved', 'embrace', 'random', 'yet',
                'depressed', 'publishing', 'candle', 'landing', 'scale', 'expertise', 'installation', 'enthusiasm',
                'globalization', 'tunnel', 'additional', 'dramatically', 'honey', 'ship', 'commitment', 'contract',
                'so-called', 'deadly', 'frequent', 'weird', 'transmit', 'owe', 'participant', 'hesitate', 'declare',
                'sweep', 'wrong', 'inevitably', 'title', 'heel', 'besides', 'emission', 'shore', 'annually', 'command',
                'soul', 'accidentally', 'surgery', 'preference', 'hopefully', 'testing', 'dairy', 'weakness', 'tap',
                'chop', 'brief', 'edition', 'incident', 'ultimate', 'opera', 'erupt', 'time', 'referee', 'unite', 'ton',
                'acquire', 'drought', 'honor', 'margin', 'eager', 'satisfy', 'probability', 'hire', 'accurately',
                'criticism', 'blanket', 'nerve', 'offense', 'humor', 'specify', 'ethnic', 'technological', 'severe',
                'launch', 'spiritual', 'organic', 'struggle', 'formerly', 'govern', 'immune', 'measurement',
                'potential', 'adequately', 'deck', 'leave', 'district', 'restore', 'progressive', 'scholarship',
                'territory', 'elegant', 'combination', 'chair', 'consideration', 'finance', 'heal', 'booking', 'plus',
                'evil', 'unknown', 'short-term', 'roughly', 'chase', 'observation', 'habitat', 'sticky', 'moreover',
                'medium', 'worst', 'sector', 'proportion', 'classify', 'colourful', 'spokesperson', 'weekly',
                'confidence', 'retain', 'picture', 'hip', 'textbook', 'stroke', 'disorder', 'decline', 'narrow',
                'humorous', 'incentive', 'concrete', 'devote', 'gaming', 'sufficient', 'strict', 'reporting',
                'entertaining', 'mode', 'ambitious', 'biological', 'insight', 'hurt', 'screen', 'consistently', 'minor',
                'forum', 'sidewalk', 'neutral', 'shortly', 'promising', 'surrounding', 'survival', 'goods', 'protein',
                'trouble', 'trading', 'astonishing', 'observer', 'decent', 'buck', 'even', 'loose', 'exception', 'rub',
                'negative', 'fully', 'scandal', 'terminal', 'accountant', 'compound', 'shock', 'lighting', 'blind',
                'collapse', 'strictly', 'capture', 'stunning', 'wise', 'permit', 'engage', 'crew', 'passionate',
                'constantly', 'innovation', 'preparation', 'grab', 'terms', 'decrease', 'switch', 'accent', 'range',
                'judgement', 'fortune', 'seat', 'rank', 'prior', 'jail', 'harbour', 'generate', 'overnight', 'comic',
                'cruise', 'indication', 'affair', 'opening', 'probable', 'outline', 'necessity', 'fix', 'failure',
                'guideline', 'packet', 'lottery', 'litre', 'strike', 'expose', 'threat', 'withdraw', 'founder',
                'senior', 'military', 'courage', 'input', 'insert', 'herb', 'primarily', 'hearing', 'disappointment',
                'sincere', 'oxygen', 'steep', 'bat', 'bitter', 'acknowledge', 'navigation', 'precede', 'contribution',
                'preserve', 'amount', 'whereas', 'fellow', 'basement', 'spectacular', 'refugee', 'highway', 'ballet',
                'purely', 'multiple', 'specialist', 'broad', 'partly', 'notion', 'associate', 'suffering', 'neat',
                'colony', 'forbid', 'desperately', 'dramatic', 'shortage', 'pension', 'try', 'nursing', 'mysterious',
                'patch', 'genetic', 'spare', 'resolve', 'championship', 'stage', 'psychologist', 'basket', 'spice',
                'core', 'negotiation', 'auction', 'worm', 'income', 'promotion', 'memorable', 'tag', 'uncertainty',
                'acid', 'root', 'accommodation', 'official', 'reveal', 'challenging', 'trace', 'participation',
                'make-up', 'bold', 'grand', 'flexible', 'arise', 'entirely', 'crop', 'inform', 'delighted', 'matching',
                'equivalent', 'spot', 'disturb', 'credit', 'seeker', 'inflation', 'prime', 'willing', 'budget',
                'divide', 'imply', 'ladder', 'senate', 'suspend', 'database', 'defender', 'hilarious', 'forward',
                'appeal', 'interpret', 'alter', 'structure', 'voluntary', 'transition', 'economics', 'gang', 'wind',
                'curious', 'artwork', 'enjoyable', 'pharmacy', 'ink', 'considerably', 'encounter', 'forecast',
                'shocking', 'depart', 'temple', 'tonne', 'distant', 'artificial', 'flash', 'display', 'pregnant',
                'revolution', 'monthly', 'rat', 'slogan', 'material', 'gradually', 'journalism', 'tropical', 'stare',
                'positive', 'firmly', 'anticipate', 'construct', 'ethical', 'vital', 'automatically', 'emerge', 'holy',
                'sophisticated', 'exotic', 'nickel', 'violence', 'agriculture', 'tone', 'chairman', 'compose',
                'largely', 'flame', 'illustrate', 'calculate', 'desert', 'tragic', 'figure', 'mate', 'pursuit', 'raw',
                'failed', 'trial', 'clarify', 'round', 'advance', 'dynamic', 'survivor', 'nearby', 'perspective',
                'folding', 'viewpoint', 'medal', 'annual', 'stream', 'ID', 'abroad', 'gig', 'enthusiastic',
                'limitation', 'wander', 'bombing', 'barely', 'disabled', 'convention', 'ongoing', 'outfit', 'gorgeous',
                'otherwise', 'passage', 'handle', 'precisely', 'majority', 'openly', 'fraction', 'receiver', 'panel',
                'prompt', 'mineral', 'loyal', 'delete', 'modest', 'bid', 'jury', 'rail', 'clerk', 'humour', 'edit',
                'van', 'icon', 'depressing', 'gender', 'minister', 'intense', 'strengthen', 'voting', 'workforce',
                'angle', 'downtown', 'session', 'tank', 'incorporate', 'charming', 'concept', 'bug', 'barrier',
                'efficiently', 'slope', 'national', 'elect', 'risky', 'craft', 'assume', 'accuse', 'destruction',
                'feel', 'target', 'free', 'thus', 'equip', 'aid', 'comprehensive', 'hell', 'beg', 'shallow', 'vary',
                'steady', 'back', 'stand', 'spill', 'intellectual', 'cancer', 'selection', 'considerable', 'cast',
                'spectator', 'volume', 'infrastructure', 'immigration', 'power', 'inherit', 'warming', 'harbor',
                'ancestor', 'steam', 'ultimately', 'myth', 'term', 'relieved', 'anxious', 'anger', 'questionnaire',
                'predictable', 'cry', 'certificate', 'equal', 'approval', 'treasure', 'demonstration', 'badge',
                'relief', 'split', 'schedule', 'commander', 'implication', 'ridiculous', 'rush', 'hunting', 'intended',
                'implement', 'resign', 'magnificent', 'guarantee', 'concentration', 'commission', 'regional',
                'threaten', 'legend', 'labour', 'undertake', 'visual', 'mosquito', 'rebuild', 'tendency', 'inspector',
                'wealth', 'scratch', 'contest', 'governor', 'abstract', 'inevitable', 'concern', 'thumb', 'objective',
                'conventional', 'skull', 'speculate', 'modify', 'dare', 'activate', 'evolve', 'purchase', 'evaluation',
                'harmful', 'editorial', 'shape', 'beside', 'wealthy', 'disappoint', 'creature', 'industrial', 'dive',
                'sample', 'cue', 'rival', 'select', 'fool', 'making', 'means', 'appropriate', 'former', 'psychology',
                'witness', 'transportation', 'adapt', 'extensive', 'vertical', 'novelist', 'starve', 'rescue', 'grant',
                'offence', 'propose', 'lung', 'contemporary', 'orchestra', 'permanent', 'motivation', 'agency', 'bear',
                'conservation', 'alarm', 'rating', 'internal', 'insurance', 'disability', 'obesity', 'registration',
                'conservative', 'estimate', 'worse', 'deliberate', 'framework', 'permanently', 'extraordinary',
                'distribution', 'position', 'wisdom', 'seek', 'offender', 'senator', 'therapist', 'load', 'document',
                'brick', 'historian', 'resort', 'lyric', 'additionally', 'newly', 'complex', 'patient', 'overcome',
                'worth', 'tune', 'joy', 'obligation', 'abandon', 'overall', 'scholar', 'undergo', 'steadily',
                'distinct', 'distribute', 'reinforce', 'map', 'hidden', 'foundation', 'secure', 'initially', 'reserve',
                'naked', 'invade', 'nutrition', 'motion', 'institute', 'low', 'swallow', 'nowadays', 'genuine', 'motor',
                'reputation', 'conduct', 'faculty', 'instant', 'scenario', 'unity', 'derive', 'graphics', 'elderly',
                'urge', 'shift', 'precious', 'delivery', 'colorful', 'pace', 'complicated', 'council', 'settler',
                'integrate', 'theft', 'multiply', 'fundamental', 'fortunate', 'maximum', 'conflict', 'analyst', 'pitch',
                'shaped', 'cabin', 'leaflet', 'bacteria', 'broadcaster', 'fuel', 'challenge', 'trap', 'significance',
                'animation', 'super', 'password', 'info', 'model', 'latest', 'subject', 'hold', 'feed', 'domestic',
                'cute', 'landscape', 'mayor', 'shelter', 'attorney', 'current', 'accompany', 'phase', 'occupy',
                'lately', 'close', 'lively', 'applicant', 'fake', 'defense', 'transfer', 'imagination', 'licence',
                'reasonably', 'stable', 'controversial', 'procedure', 'creation', 'constant', 'convenience', 'valid',
                'absolute', 'differ', 'crash', 'outcome', 'upper', 'sometime', 'miner', 'evolution', 'controversy',
                'transform', 'audio', 'shot', 'nightmare', 'negotiate', 'fabulous', 'carbon', 'institution', 'high',
                'nasty', 'consult', 'coverage', 'project', 'emotional', 'academic', 'teen', 'track', 'restrict',
                'associated', 'delay', 'electronics', 'goodness', 'remark', 'initiative', 'mass', 'illustration',
                'install', 'visa', 'subsequent', 'pile', 'dig', 'self', 'radiation', 'discount', 'notebook', 'attempt',
                'feedback', 'beneficial', 'finding', 'AIDS', 'labor', 'organ', 'kindergarten', 'illusion', 'justify',
                'issue', 'perceive', 'broadcast', 'mosque', 'pose', 'presence', 'steel', 'dull', 'martial', 'resist',
                'consultant', 'initial', 'asset', 'sum', 'privacy', 'delight', 'fault', 'innovative', 'terrorist',
                'comprise', 'obey', 'extent', 'step', 'opponent', 'ownership', 'external', 'spoil', 'vitamin',
                'emphasize', 'miserable', 'component', 'shame', 'apology', 'furthermore', 'division', 'examination',
                'empire', 'fever', 'rapid', 'contribute', 'sympathetic', 'hypothesis', 'essentially', 'usage', 'gallon',
                'evident', 'unfold', 'recovery', 'racial', 'house', 'fossil', 'assure', 'extend', 'league', 'workshop',
                'solar', 'fund', 'harm', 'praise', 'revenue', 'mission', 'upward', 'drag', 'trait', 'extension',
                'shocked', 'defend', 'tension', 'origin', 'mount', 'confusing', 'relieve', 'grade', 'characteristic',
                'depth', 'defeat', 'facility', 'boost', 'stuff', 'tackle', 'part-time', 'saving', 'protection',
                'criticize', 'helmet', 'ideal', 'detect', 'awareness', 'potentially', 'representative', 'stance',
                'likewise', 'cancel', 'armed', 'terrorism', 'inquiry', 'principal', 'print', 'breast', 'genius',
                'realistic', 'register', 'stiff', 'adequate', 'conscious', 'partnership', 'plain', 'object', 'cliff',
                'whom', 'retirement', 'federal', 'favor', 'palm', 'resident', 'temporary', 'widespread', 'make',
                'litter', 'unique', 'interaction', 'publication', 'logo', 'float', 'graphic', 'observe', 'line', 'blow',
                'chart', 'gesture', 'deliberately', 'convincing', 'headquarters', 'consequently', 'outstanding',
                'wound', 'cure', 'parliament', 'mortgage', 'excessive', 'price', 'being', 'regard', 'reckon', 'diverse',
                'disk', 'decorate', 'species', 'remarkably', 'accuracy', 'afterward', 'fundamentally', 'approve',
                'lane', 'sexy', 'firework', 'castle', 'suburb', 'canal', 'broadly', 'fragment', 'junior', 'extract',
                'significant', 'mechanism', 'urgent', 'slip', 'civilization', 'homeless', 'parade', 'motivate',
                'fabric', 'basically', 'overseas', 'limited', 'bullet', 'criterion', 'circumstance', 'unexpected',
                'somewhat', 'demand', 'via', 'agenda', 'but', 'dime', 'association', 'jet', 'afterwards', 'monster',
                'altogether', 'accurate', 'comparative', 'recruit', 'loan', 'mixed', 'ruin', 'fold', 'wrap',
                'tournament', 'pointed', 'popularity', 'process', 'duration', 'aspect', 'stall', 'rubber', 'closely',
                'wire', 'rate', 'welfare', 'interval', 'existence', 'elsewhere', 'sentence', 'critic', 'fulfill',
                'recall', 'instantly', 'impatient', 'major', 'scream', 'following', 'chief', 'sibling', 'file', 'value',
                'spokesman', 'increasingly', 'restriction', 'wolf', 'speed', 'tragedy', 'operator', 'zone', 'visible',
                'recession', 'pill', 'patience', 'distinguish', 'cite', 'pity', 'operate', 'debate', 'identical',
                'literally', 'melt', 'priority', 'assessment', 'dismiss', 'beat', 'truly', 'cop', 'medication',
                'briefly', 'penalty', 'troop', 'infection', 'enhance', 'thorough', 'golden', 'detail', 'expense',
                'full-time', 'kit', 'hunger', 'routine', 'therapy', 'output', 'enquiry', 'slide', 'aged', 'puzzle',
                'cowboy', 'trust', 'virtual', 'sustainable', 'long-term', 'bargain', 'trillion', 'rental', 'emphasis',
                'ethic', 'thesis', 'format', 'cable', 'wrist', 'rhythm', 'citizen', 'arms', 'aside', 'household',
                'terribly', 'deserve', 'wherever', 'crisis', 'divorce', 'creativity', 'elbow', 'convinced',
                'membership', 'nevertheless', 'actual', 'robbery', 'dominate', 'tissue', 'impressed', 'stimulate',
                'impress', 'assistance', 'resolution', 'sequence', 'elementary', 'temporarily', 'teens', 'upwards',
                'deposit', 'opposition', 'minority', 'scare', 'impose', 'vast', 'pride', 'committee', 'satisfaction',
                'casual', 'bet', 'downwards', 'awkward', 'victory', 'seminar', 'balloon', 'monument', 'assumption',
                'prohibit', 'account', 'exploit', 'disagreement', 'lower', 'requirement', 'desperate', 'critical',
                'lifetime', 'unconscious', 'reach', 'debt', 'establish', 'concerned', 'precise', 'executive', 'venue',
                'deny', 'flavour', 'spokeswoman', 'relevant', 'master', 'speculation', 'severely', 'clinic', 'forgive',
                'assess', 'protester', 'moving', 'philosophy', 'deadline', 'county', 'exceed', 'corporate', 'fond',
                'rocket', 'norm', 'professional', 'metaphor', 'dot', 'unacceptable', 'hunt', 'résumé', 'hook',
                'expedition', 'recognition', 'pick', 'settle', 'universal', 'economist', 'apparently', 'discipline',
                'incorrect', 'housing', 'investment', 'donation', 'honesty', 'screening', 'independence', 'shooting',
                'whisper', 'anxiety', 'anniversary', 'sporting', 'moral', 'index', 'regret', 'addiction', 'joint',
                'maintain', 'shade', 'placement', 'apparent', 'determination', 'hence', 'recover', 'corridor', 'choir',
                'logical', 'isolate', 'bush', 'tsunami', 'physician', 'clip', 'minimum', 'greatly', 'function',
                'phenomenon', 'urban', 'accommodate', 'curve', 'submit', 'variation', 'sensitive', 'envelope', 'way',
                'shall', 'trip', 'entire', 'sponsorship', 'commonly', 'pure', 'manufacture', 'retail', 'invasion',
                'excuse', 'tribe', 'status', 'completion', 'pupil', 'expansion', 'pursue', 'dependent', 'capable',
                'border', 'adopt', 'coincidence', 'inner', 'disc', 'efficient', 'diversity', 'defence', 'dozen',
                'slave', 'reasonable', 'universe', 'stretch', 'exclude', 'fraud', 'inch', 'remarkable', 'burn', 'rid',
                'rely', 'dealer', 'scheme', 'tear', 'attachment', 'spread', 'demonstrate', 'eliminate', 'artistic',
                'presidential', 'rise', 'crucial', 'fame', 'rapidly', 'sponsor', 'satellite', 'cheek', 'estate', 'rob',
                'healthcare', 'convert', 'widely', 'tough', 'regulate', 'peer', 'sense', 'distract', 'wildlife',
                'marathon', 'cell', 'date', 'lord', 'host', 'comfort', 'extreme', 'mechanic', 'very', 'affordable',
                'tale', 'surgeon', 'outer', 'frequency', 'panic', 'critically', 'freedom', 'entrepreneur', 'level',
                'possess', 'alien', 'portion', 'conspiracy', 'signature', 'lean', 'detailed', 'offensive', 'bent',
                'consistent', 'principle', 'blame', 'wage', 'absorb', 'civil', 'thoroughly', 'infer', 'lens',
                'extensively', 'greenhouse', 'approach', 'suspect', 'progress', 'surround', 'ashamed', 'insist',
                'perception', 'freely', 'gene', 'ambulance', 'cope', 'isolated', 'interrupt', 'sympathy', 'wheat',
                'emotionally', 'flavor', 'found', 'balanced', 'package', 'consumption', 'formation', 'certainty',
                'massive', 'compulsory', 'terror', 'congress', 'opposed', 'prospect', 'draft', 'genre', 'sufficiently',
                'optimistic', 'fantasy', 'investigation', 'subsequently', 'shadow', 'arrow', 'administration',
                'accomplish', 'punk', 'fare', 'investor', 'acceptable', 'reduction', 'rural', 'catch', 'evaluate',
                'workplace', 'recruitment', 'silk', 'desire', 'expectation', 'capacity', 'bias', 'racism', 'depression',
                'plot', 'stock', 'chain', 'grocery', 'racist', 'dominant', 'swear', 'fee', 'fulfil', 'appropriately',
                'publicity', 'dishonest', 'inspire', 'confusion', 'exposure', 'programming', 'hollow', 'marker',
                'battle', 'dump', 'enable', 'gay', 'confess', 'judgment', 'slight', 'convey', 'oppose', 'beyond',
                'downward', 'cheer', 'pause', 'terrify', 'honour', 'spite', 'occasionally', 'deeply', 'globe',
                'license', 'silence', 'firm', 'era', 'whoever', 'composer', 'literary', 'athletic', 'feather', 'bound',
                'ensure', 'amusing', 'trigger', 'unfortunate', 'faith', 'offend', 'address', 'regulation', 'aircraft',
                'useless', 'inhabitant', 'mistake', 'curriculum', 'assign', 'gain', 'satisfied', 'rose', 'circuit',
                'cave', 'decoration', 'democratic', 'skilled', 'monitor', 'classic', 'occupation', 'bill',
                'exploration', 'revision', 'discourage', 'parallel']

    words_c1 = ['lawmaker', 'constitute', 'niche', 'submission', 'intact', 'endure', 'gross', 'pioneer', 'rebel',
                'limb', 'allocation', 'gathering', 'film-maker', 'aftermath', 'soak', 'collaborate', 'distort',
                'beverage', 'academy', 'activist', 'proclaim', 'regulator', 'occasional', 'align', 'rape', 'radar',
                'consolidate', 'spin', 'inclined', 'capability', 'remedy', 'consent', 'relevance', 'simulation',
                'analogy', 'acre', 'accused', 'applicable', 'plunge', 'infect', 'funeral', 'preside', 'postwar',
                'counter', 'initiate', 'harvest', 'intermediate', 'dedicated', 'noon', 'merchant', 'correlate',
                'guidance', 'appealing', 'snap', 'exit', 'contempt', 'agricultural', 'migration', 'autonomy',
                'correction', 'collective', 'motorist', 'long-standing', 'medieval', 'tumor', 'intimate', 'cemetery',
                'invisible', 'acceptance', 'kidney', 'gravity', 'amend', 'indictment', 'commentary', 'nod', 'fate',
                'complement', 'weed', 'misery', 'retreat', 'assault', 'productive', 'ecological', 'minute',
                'bankruptcy', 'transcript', 'mobile', 'equality', 'closure', 'cabinet', 'directory', 'buffer',
                'citizenship', 'councillor', 'reproduction', 'thread', 'nonetheless', 'boundary', 'liberal', 'inhibit',
                'lengthy', 'bow', 'contend', 'militant', 'accelerate', 'neighbouring', 'diagnose', 'privilege',
                'transparency', 'congregation', 'bass', 'grace', 'misleading', 'mathematical', 'compensation',
                'arbitrary', 'eager', 'conversion', 'constitution', 'disposal', 'immense', 'plea', 'deputy', 'cautious',
                'slot', 'atrocity', 'dissolve', 'melody', 'authentic', 'decisive', 'realm', 'structural', 'segment',
                'companion', 'aesthetic', 'top', 'yell', 'grid', 'robust', 'accountability', 'spine', 'presumably',
                'provoke', 'humanity', 'absent', 'constitutional', 'productivity', 'booking', 'bulk', 'philosopher',
                'forthcoming', 'operational', 'turnover', 'sound', 'mask', 'burden', 'allowance', 'brutal', 'dictator',
                'backing', 'meantime', 'secondly', 'discourse', 'successive', 'insufficient', 'strain', 'clinical',
                'entitle', 'mobilize', 'explicit', 'reform', 'hostage', 'manuscript', 'massacre', 'whip', 'amid',
                'glory', 'continually', 'republic', 'tactical', 'withdrawal', 'horn', 'aspire', 'forth', 'stir',
                'premier', 'preservation', 'buck', 'orientation', 'manifest', 'combat', 'just', 'ironic', 'inspect',
                'terminal', 'precedent', 'rally', 'cease', 'straightforward', 'timber', 'naval', 'bureaucracy',
                'versus', 'expenditure', 'triumph', 'embassy', 'administrative', 'plead', 'reven', 'mature', 'barrel',
                'unprecedented', 'remains', 'hazard', 'peculiar', 'injustice', 'empirical', 'ease', 'setup',
                'worthwhile', 'appreciation', 'decision-making', 'exploitation', 'adaptation', 'dense', 'displace',
                'jurisdiction', 'trio', 'stabilize', 'desirable', 'detection', 'burst', 'substitute', 'carve', 'intake',
                'villager', 'assemble', 'whilst', 'communist', 'alike', 'testimony', 'sphere', 'hardware', 'civilian',
                'attendance', 'rotation', 'whatsoever', 'judicial', 'injection', 'bat', 'consecutive', 'dominance',
                'distinctive', 'synthesis', 'taxpayer', 'doctrine', 'costly', 'minimize', 'architectural', 'residence',
                'overwhelming', 'mob', 'carriage', 'essence', 'scrutiny', 'supervision', 'abuse', 'instrumental',
                'pension', 'renew', 'footage', 'patch', 'beast', 'solidarity', 'sovereignty', 'spare', 'spouse',
                'empower', 'dictate', 'endorse', 'foreigner', 'divert', 'auction', 'specialized', 'acid', 'syndrome',
                'memo', 'trace', 'rumor', 'log', 'flourish', 'resemble', 'shoot', 'surgical', 'consultation', 'solely',
                'reside', 'respective', 'morality', 'resume', 'insult', 'involvement', 'distinction', 'aggression',
                'liberation', 'integration', 'overly', 'sentiment', 'youngster', 'solo', 'strategic', 'incarcerate',
                'organizational', 'midst', 'cynical', 'hopeful', 'entity', 'nest', 'march', 'plug', 'mere', 'intent',
                'alliance', 'punch', 'processor', 'verbal', 'grin', 'facilitate', 'filter', 'propaganda', 'idiot',
                'concede', 'marine', 'objection', 'engagement', 'acquisition', 'warrior', 'bay', 'biography', 'arena',
                'ranking', 'settlement', 'commissioner', 'counselor', 'verdict', 'hostile', 'supplement', 'linger',
                'chamber', 'accordance', 'aspiration', 'acute', 'sketch', 'maximize', 'standing', 'striking',
                'flexibility', 'petition', 'yield', 'hierarchy', 'prejudice', 'violate', 'shrink', 'await', 'attribute',
                'assembly', 'dynamic', 'forge', 'coalition', 'exile', 'simultaneously', 'testify', 'revival',
                'systematic', 'ensue', 'comparable', 'consistency', 'adverse', 'gig', 'casino', 'transaction', 'wholly',
                'endeavour', 'induce', 'circulate', 'pastor', 'formula', 'congratulate', 'trophy', 'influential',
                'skeptical', 'gut', 'tactic', 'oblige', 'spectacle', 'assurance', 'spectrum', 'boast', 'delicate',
                'assassination', 'earnings', 'aluminum', 'net', 'tribal', 'deem', 'consciousness', 'outsider',
                'meaningful', 'verify', 'upcoming', 'momentum', 'wit', 'suite', 'accordingly', 'denounce',
                'shareholder', 'stereotype', 'corresponding', 'originate', 'stem', 'donor', 'sin', 'vicious', 'listing',
                'craft', 'differentiate', 'storage', 'prospective', 'methodology', 'contrary', 'abortion',
                'restoration', 'invoke', 'dual', 'cluster', 'complexity', 'optical', 'soar', 'sheer', 'enterprise',
                'dispose', 'charm', 'suspicious', 'interactive', 'latter', 'resignation', 'stab', 'battlefield',
                'coincide', 'workout', 'conception', 'leap', 'autumn', 'encouraging', 'hydrogen', 'intellectual',
                'inequality', 'liter', 'vein', 'liver', 'legacy', 'adolescent', 'incarceration', 'crown', 'presently',
                'prescribe', 'fundraising', 'regime', 'competent', 'exclusion', 'thought-provoking', 'saint', 'seal',
                'thereafter', 'total', 'grip', 'characterize', 'leak', 'fairness', 'echo', 'tuition', 'proceedings',
                'cutting', 'outlet', 'magnificent', 'marginal', 'integrity', 'sack', 'terrific', 'amendment',
                'protocol', 'humanitarian', 'variable', 'default', 'apparatus', 'parameter', 'ash', 'columnist',
                'competence', 'handling', 'breakdown', 'enact', 'confront', 'rear', 'array', 'legislature', 'stimulus',
                'lesbian', 'toss', 'harsh', 'elaborate', 'enforcement', 'enrich', 'prominent', 'seldom', 'motive',
                'pledge', 'absurd', 'stumble', 'mercy', 'render', 'ideological', 'literacy', 'pregnancy', 'legendary',
                'bleed', 'slash', 'symbolic', 'designate', 'accomplishment', 'horizon', 'prestigious', 'deploy',
                'shrug', 'anonymous', 'vacuum', 'dependence', 'fit', 'landmark', 'province', 'spy', 'overturn',
                'disrupt', 'explosive', 'fragile', 'compel', 'transparent', 'abundance', 'halt', 'presidency', 'prey',
                'depict', 'damaging', 'defect', 'interior', 'albeit', 'firearm', 'correspond', 'stability', 'arguably',
                'credibility', 'wipe', 'representation', 'reassure', 'slavery', 'raid', 'contemplate', 'residue',
                'senator', 'thankfully', 'anchor', 'coup', 'recipient', 'mining', 'experimental', 'counterpart',
                'dignity', 'explicitly', 'enquire', 'quest', 'overlook', 'density', 'exclusively', 'thrilled',
                'declaration', 'bare', 'eternal', 'frustrating', 'rip', 'lawn', 'crawl', 'curiosity', 'elite', 'fatal',
                'inclusion', 'destructive', 'fine', 'merge', 'coordinate', 'ironically', 'correspondent', 'suspicion',
                'supportive', 'keen', 'allocate', 'intersection', 'civic', 'oral', 'flawed', 'engaging', 'removal',
                'assertion', 'miracle', 'handful', 'nonprofit', 'separation', 'endeavor', 'instruct', 'faculty',
                'canvas', 'pirate', 'revenge', 'extremist', 'outlook', 'substantial', 'inflict', 'embed', 'bizarre',
                'high-profile', 'insider', 'legislative', 'suspension', 'parish', 'capitalism', 'correspondence',
                'minimal', 'overwhelm', 'poll', 'exaggerate', 'specification', 'drown', 'gambling', 'portray',
                'problematic', 'ally', 'republicn.', 'flesh', 'neighboring', 'premise', 'slam', 'skip', 'predator',
                'prosecute', 'contender', 'surge', 'deed', 'peak', 'spell', 'cattle', 'notorious', 'disastrous',
                'enrol', 'compile', 'embarrassment', 'torture', 'contradiction', 'width', 'inquire', 'attorney',
                'halfway', 'counseling', 'protective', 'residential', 'undoubtedly', 'compelling', 'devise', 'unify',
                'preach', 'vulnerable', 'postpone', 'occurrence', 'guilt', 'verse', 'inject', 'sanction', 'allege',
                'probe', 'recount', 'predecessor', 'prevail', 'regain', 'banner', 'glorious', 'renowned', 'refusal',
                'rage', 'genocide', 'non-profit', 'heighten', 'laser', 'twist', 'confirmation', 'fleet', 'catalog',
                'ideology', 'profitable', 'fibre', 'roster', 'commentator', 'bail', 'tremendous', 'specimen',
                'filmmaker', 'seize', 'affection', 'administrator', 'commerce', 'substitution', 'haunt', 'activation',
                'sigh', 'monk', 'desktop', 'stake', 'vessel', 'meditation', 'dismissal', 'virtue', 'statistical',
                'passive', 'surplus', 'prevention', 'prescription', 'apparel', 'cooperate', 'resistance', 'descent',
                'pond', 'backup', 'beloved', 'revolutionary', 'broadband', 'supposedly', 'simulate', 'betray',
                'archive', 'thrive', 'cooperative', 'rod', 'shatter', 'cultivate', 'divine', 'longtime',
                'discrimination', 'span', 'content', 'disclosure', 'infamous', 'proceeding', 'machinery', 'adhere',
                'prosecutor', 'credible', 'theatrical', 'substantially', 'strip', 'indicator', 'constraint',
                'capitalist', 'peasant', 'squad', 'utilize', 'confine', 'reluctant', 'electoral', 'auto',
                'intervention', 'processing', 'practitioner', 'uphold', 'exert', 'parental', 'enroll', 'spark',
                'tighten', 'obsess', 'dose', 'willingness', 'ambassador', 'deployment', 'implementation', 'behavioral',
                'gallon', 'nursery', 'weaken', 'courtesy', 'tenant', 'beneficiary', 'ruling', 'complication', 'appoint',
                'debris', 'counselling', 'terminate', 'mobility', 'varied', 'reverse', 'dawn', 'sole', 'circulation',
                'detain', 'warrant', 'franchise', 'scattered', 'harmony', 'screw', 'obsession', 'timely', 'widen',
                'thereby', 'clash', 'say', 'venture', 'frustration', 'memoir', 'municipal', 'tackle', 'tolerance',
                'admission', 'beneath', 'clarity', 'unconstitutional', 'humble', 'deficiency', 'rock', 'fixture',
                'memorial', 'trail', 'evolutionary', 'diplomat', 'liberty', 'reminder', 'documentation', 'feat',
                'principal', 'philosophical', 'sustain', 'interfere', 'kingdom', 'legislation', 'generic', 'module',
                'formulate', 'shipping', 'solicitor', 'landlord', 'supervise', 'incidence', 'socialist', 'outbreak',
                'dilemma', 'intensive', 'notify', 'marketplace', 'rational', 'merger', 'availability', 'coordinator',
                'disturbing', 'erect', 'blessing', 'efficiency', 'interference', 'accumulation', 'superior', 'novel',
                'parliament', 'provincial', 'patron', 'retrieve', 'collision', 'worship', 'discretion', 'nominee',
                'conserve', 'strive', 'feminist', 'exclusive', 'interim', 'calculation', 'devastate', 'conscience',
                'breach', 'conviction', 'ritual', 'veteran', 'privatization', 'inventory', 'thoughtful', 'deteriorate',
                'mandate', 'extract', 'demon', 'bishop', 'cognitive', 'slap', 'proceeds', 'vow', 'crude', 'pronounced',
                'freshman', 'sake', 'pit', 'functional', 'militia', 'catalogue', 'aide', 'commodity', 'strand',
                'rejection', 'corrupt', 'irrelevant', 'pump', 'refuge', 'breakthrough', 'enthusiast', 'superb',
                'homeland', 'undermine', 'manipulate', 'subscription', 'intensity', 'undergraduate', 'merit',
                'succession', 'establishment', 'allegation', 'favourable', 'domain', 'magnetic', 'fiber', 'monopoly',
                'lifelong', 'excellence', 'flee', 'threshold', 'tender', 'premium', 'contention', 'diplomatic', 'tide',
                'patent', 'set-up', 'benchmark', 'bounce', 'ratio', 'pop', 'buddy', 'foster', 'lawsuit', 'referendum',
                'mutual', 'reportedly', 'seemingly', 'cop', 'maintenance', 'faction', 'rookie', 'ignorance', 'toxic',
                'quota', 'transit', 'caution', 'boom', 'heritage', 'liable', 'loom', 'merely', 'sensation',
                'sensitivity', 'rental', 'reflection', 'congressional', 'adjacent', 'bonus', 'projection', 'intervene',
                'crush', 'stark', 'identification', 'defy', 'composition', 'trademark', 'profound', 'lesser', 'unveil',
                'notably', 'devil', 'grief', 'configuration', 'effectiveness', 'summit', 'endorsement', 'evoke',
                'whereby', 'sexuality', 'casualty', 'long-time', 'blend', 'outing', 'scope', 'administer', 'handy',
                'hatred', 'vocal', 'persist', 'guerrilla', 'disruption', 'comply', 'passing', 'successor', 'validity',
                'personnel', 'respectively', 'lineup', 'contractor', 'cater', 'deposit', 'cling', 'reasoning', 'swing',
                'disclose', 'preliminary', 'accessible', 'presume', 'opt', 'duo', 'tobacco', 'glimpse',
                'classification', 'newsletter', 'defensive', 'confrontation', 'lad', 'interface', 'beam', 'drain',
                'distress', 'investigator', 'dedication', 'colonial', 'gaze', 'namely', 'chunk', 'rifle', 'attain',
                'reconstruction', 'inmate', 'audit', 'optimism', 'harassment', 'lethal', 'imagery', 'chronic',
                'custody', 'vice', 'coastal', 'backdrop', 'delegation', 'mandatory', 'alignment', 'trauma',
                'proposition', 'councilor', 'frustrated', 'linear', 'magnitude', 'irony', 'prosperity', 'driving',
                'rhetoric', 'creator', 'advocate', 'encouragement', 'reproduce', 'confession', 'widow', 'corruption',
                'inappropriate', 'excess', 'hail', 'pipeline', 'diagnosis', 'indulge', 'sophomore', 'breed', 'missile',
                'cargo', 'creep', 'applaud', 'execution', 'trustee', 'hook', 'toll', 'accountable', 'viable', 'reign',
                'turnout', 'squeeze', 'rebellion', 'query', 'dumb', 'bind', 'prevalence', 'logic', 'allegedly',
                'remainder', 'asylum', 'inadequate', 'replacement', 'vibrant', 'conceal', 'well', 'provision', 'assert',
                'rehabilitation', 'tribute', 'compromise', 'critique', 'subscriber', 'ego', 'subtle', 'well-being',
                'isolation', 'subsidy', 'integral', 'intensify', 'imminent', 'mainstream', 'choir', 'stun', 'loop',
                'partially', 'physician', 'dip', 'deprive', 'dam', 'abolish', 'utility', 'integrated', 'epidemic',
                'equation', 'riot', 'imprisonment', 'pad', 'intriguing', 'prosecution', 'articulate', 'aluminium',
                'conquer', 'burial', 'vanish', 'mill', 'commence', 'suck', 'favorable', 'treaty', 'patrol',
                'realization', 'gear', 'fluid', 'suppress', 'alert', 'cult', 'evacuate', 'mainland', 'regulatory',
                'debut', 'embody', 'nonsense', 'descend', 'collaboration', 'bless', 'spam', 'frankly', 'nationwide',
                'secular', 'glance', 'theology', 'behalf', 'deficit', 'inspiration', 'presidential', 'condemn',
                'cocktail', 'superintendent', 'dimension', 'line-up', 'conceive', 'bench', 'elevate', 'oversee',
                'discard', 'worthy', 'accusation', 'ballot', 'offspring', 'ward', 'discharge', 'grind', 'restraint',
                'trailer', 'transmission', 'weave', 'fierce', 'dub', 'underlying', 'diminish', 'instinct', 'odds',
                'nomination', 'tempt', 'angel', 'inspection', 'loyalty', 'consensus', 'magical', 'compensate', 'embark',
                'suicide', 'inherent', 'copyright', 'smash', 'vague', 'authorize', 'pathway', 'counsellor', 'tolerate',
                'selective', 'alien', 'offering', 'theoretical', 'infant', 'insertion', 'sacred', 'sue', 'noble',
                'suburban', 'delegate', 'accumulate', 'pulse', 'ministry', 'absence', 'sacrifice', 'correlation',
                'legitimate', 'manipulation', 'rotate', 'likelihood', 'felony', 'nominate', 'compassion', 'incur',
                'governance', 'mentor', 'imprison', 'violation', 'drift', 'predominantly', 'coordination', 'utterly',
                'blast', 'precision', 'radical', 'notable', 'sceptical', 'adjustment', 'convict', 'expire', 'hint',
                'inability', 'crystal', 'kidnap', 'ray', 'outrage', 'charter', 'terrain', 'lap', 'sword', 'compliance',
                'fade', 'hostility', 'tribunal', 'encompass', 'supreme', 'moderate', 'recruitment', 'transformation',
                'persistent', 'junction', 'escalate', 'partial', 'supervisor', 'constituency', 'countless', 'troubled',
                'browser', 'vulnerability', 'parliamentary', 'regardless', 'large-scale', 'emergence', 'detention',
                'institutional', 'blade', 'flaw', 'indigenous', 'texture', 'justification', 'upgrade', 'lobby', 'shed',
                'chaos', 'warfare', 'neglect', 'pole', 'arm', 'grasp', 'revive', 'dispute', 'amateur', 'educator',
                'contributor', 'adoption', 'endless', 'execute', 'license', 'concession', 'grave', 'copper',
                'reliability', 'exceptional', 'rumour', 'surrender', 'trigger', 'revelation', 'post-war', 'steer',
                'portfolio', 'denial', 'enforce', 'surveillance', 'confer', 'layout', 'appetite', 'situated',
                'spotlight', 'compute', 'psychiatric', 'magistrate', 'eligible', 'tenure', 'modification', 'fiscal',
                'serial', 'readily', 'warehouse']


    def word_count(row, words):
        counter = 0
        sub_words = row['subs'].split()
        for x in sub_words:
            for y in words:
                if x == y:
                    counter += 1
        part = counter / len(sub_words)
        return part


    def prob(probabilities):
        token = 0
        max = -1
        level = ['A2', 'B1', 'B2', 'C1']

        for x in range(len(probabilities[0])):
            if probabilities[0][x] > token:

                token = probabilities[0][x]
                max = x

        return level[max]


    def probabilities(film):
        sub = transformation(film)
        
        sub_df = pd.DataFrame([sub], columns=['subs'])
        sub_df['A1'] = sub_df.apply(word_count, axis=1, words=words_a1)
        sub_df['A2'] = sub_df.apply(word_count, axis=1, words=words_a2)
        sub_df['B1'] = sub_df.apply(word_count, axis=1, words=words_b1)
        sub_df['B2'] = sub_df.apply(word_count, axis=1, words=words_b2)
        sub_df['C1'] = sub_df.apply(word_count, axis=1, words=words_c1)
        vec_sub = vectorizer.transform(sub_df['subs']).toarray()
        col_vec_sub = vectorizer.get_feature_names_out()
        df_test_vec = pd.DataFrame(vec_sub, columns=col_vec_sub)
        df_test = sub_df.join(df_test_vec, lsuffix='_left', rsuffix='_right')
        features = df_test.drop(['subs'], axis=1)
        probabilities = logreg.predict_proba(features)
        result = prob(probabilities)
        return result


    result = probabilities(texts)
    st.write(result)
